"""Initial migration

Revision ID: 5964e7e4c0a5
Revises: 
Create Date: 2024-08-16 11:13:56.412778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5964e7e4c0a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_products')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=345),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=345),
               nullable=True)

    op.create_table('_alembic_tmp_products',
    sa.Column('id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('name', sa.VARCHAR(length=345), nullable=False),
    sa.Column('type', sa.VARCHAR(length=30), nullable=True),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('scount', sa.INTEGER(), nullable=False),
    sa.Column('mcount', sa.INTEGER(), nullable=False),
    sa.Column('lcount', sa.INTEGER(), nullable=False),
    sa.Column('xlcount', sa.INTEGER(), nullable=False),
    sa.Column('xxlcount', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.VARCHAR(length=1000), nullable=False),
    sa.Column('photo', sa.VARCHAR(length=345), nullable=False),
    sa.Column('hover_image', sa.VARCHAR(length=345), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###
